# Generated by Django 5.1.1 on 2024-09-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuralnet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='architectureprediction',
            old_name='predicted_class',
            new_name='predicted_label',
        ),
        migrations.RenameField(
            model_name='architectureprediction',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='architectureprediction',
            name='confidence_scores',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='architectureprediction',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
